export enum ClotheCategories {
  TOP_AND_T_SHIRTS = "TOP_AND_T_SHIRTS",
  SWEATER_AND_HOODIES = "SWEATER_AND_HOODIES",
  BOTTOMS_AND_LEGGINGS = "BOTTOMS_AND_LEGGINGS",
  JUMPSUITS_AND_DRESSES = "JUMPSUITS_AND_DRESSES",
  JACKETS_AND_COATS = "JACKETS_AND_COATS",
  SHORTS_AND_SKIRTS = "SHORTS_AND_SKIRTS",
  SHOES_AND_SOCKS = "SHOES_AND_SOCKS",
  SUIT = "SUIT",
  ACCESSORIES = "ACCESSORIES",
  OTHER = "OTHER",
}
